### PR TITLE
LRQA-64278 Fix Forms#SubmitFormAfterEditingFields

### PR DESCRIPTION
**Pull request by brunofariasdeo**
https://issues.liferay.com/browse/LRQA-64278

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by brunofariasdeo** [comment]
ci:test:forms

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by brunofariasdeo** [comment]
ci:forward

**Pull request closed without merging**
